package com.example.Practica.persistence.entity.user.permissions;

public enum PermissionEnum {

    // PERMISOS DE USUARIO
    READ_ALL_USERS,
    READ_USERS,
    CREATE_USERS,
    UPDATE_USERS,
    DELETE_USERS,

    // PERMISOS DE ADMIN
    READ_ALL_ADMINS,
    READ_ADMINS,
    CREATE_ADMINS,
    UPDATE_ADMINS,
    DELETE_ADMINS,

    // PERMISOS DE CLIENTE
    READ_ALL_CLIENTS,
    READ_CLIENTS,
    CREATE_CLIENTS,
    UPDATE_CLIENTS,
    DELETE_CLIENTS,

    // PERMISOS DE VENDEDOR
    READ_ALL_SELLERS,
    READ_SELLERS,
    CREATE_SELLERS,
    UPDATE_SELLERS,
    DELETE_SELLERS,

    // PERMISOS DE GUEST
    READ_GUEST
}
